enum UserRole {
    admin
    mechanic
    customer
}

Table Usuarios {
    id_usuario serial [pk]
    user_name varchar(50) [not null, unique]
    email varchar(100) [not null, unique]
    password varchar(255) [not null]
    direccion varchar(255)
    telefono varchar(15)
    role UserRole [not null] 
    is_active boolean [not null,default: true]
    created_at timestamp [default: `now()`, not null] //fecha de creacion
    updated_at timestamp [default: `now()`] //fecha de actualizacion
    metodo_pago varchar [not null]
}

Table Producto {
    id_producto serial [pk]
    electrodomesticos varchar
    deportes varchar
    ropa varchar
    video_juegos varchar 
    herramientas varchar
    juguetes varchar
    accesorios varchar

}

Table MetodoPago {
    id_metodo_pago serial [pk]
    tipo_banco varchar [not null, unique]
    tipo_cuenta varchar [not null, unique]
    tipo_tarjeta varchar [not null, unique]
    usuario_id int [ref: > Usuarios.id_usuario, not null] // Relacion con la tabla usuarios
    
    
}

Table Redireccionar {
    id_redireccionar serial [pk]
    busqueda varchar(255)
    compras_frecuentes varchar(255)
    usuario_id int [ref: > Usuarios.id_usuario] // Relacion con la tabla usuarios
    producto_id int [ref: > Producto.id_producto] // Relacion con la tabla productos
}


Table Notificaciones {
    id_notificaiones serial [pk]
    tipo_notificacion varchar(100) [not null]
    mensaje text [not null]
    usuario_id int [ref: > Usuarios.id_usuario, not null] // Relacion con la tabla usuarios
    creado_en timestamp [default: `now()`, not null] //fecha de creacion
    visto boolean [default: false, not null] // Indica si la notificacion ha sido leida
}

Table Envios {
    id_envios serial [pk]
    direccion_envio varchar(255) [not null]
    fecha_envio timestamp [default: `now()`, not null] //fecha de envio
    estado_envio varchar(50) [not null] //estado del envio
    usuario_id int [ref: > Usuarios.id_usuario, not null] // Relacion con la tabla usuarios
}

Table Comentarios {
    id_comentarios serial [pk]
    contenido text [not null]
    calificacion int [not null, note: 'Calificación del 1 al 5']
    usuario_id int [ref: > Usuarios.id_usuario, not null] // Relacion con la tabla usuarios
    producto_id int [ref: > Producto.id_producto, not null] // Relacion con la tabla productos
    creado_en timestamp [default: `now()`, not null] //fecha de creacion
}